import { test, expect } from '@playwright/test'

test('sandbox backend previews, approves, retries and versions result emails', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('Email address').fill('e2e.lecturer@example.com')
  await page.getByLabel('Password').fill('TestPass123!')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await page.goto('/courses')
  await page.getByText('EMAIL-E2E', { exact: true }).click()
  await page.getByRole('link', { name: /Email delivery sandbox/ }).click()
  const panel = page.locator('.email-panel')
  const record = (number: string) =>
    panel
      .locator('.email-record')
      .filter({ has: page.getByRole('heading', { name: new RegExp(number) }) })
      .first()
  const approval = record('90000001')
  await expect(approval).toContainText('Awaiting approval')
  await approval.getByText('Preview stored email', { exact: true }).click()
  await expect(approval).toContainText('approval@example.invalid')
  await expect(approval.locator('pre')).toContainText(/75(?:\.00)? \/ 100(?:\.00)?/)
  await approval.getByRole('button', { name: 'Approve email', exact: true }).click()
  await expect(approval.locator('.delivery-status')).toHaveText('Queued')

  const missing = record('90000002')
  await missing.getByRole('button', { name: 'Retry failed email' }).click()
  await expect(panel.getByRole('alert')).toContainText('The student has no email address.')
  const failed = record('90000003')
  await failed.getByRole('button', { name: 'Retry failed email' }).click()
  await expect(failed.locator('.delivery-status')).toHaveText('Queued')
  const unknown = record('90000004')
  await expect(unknown.getByRole('button', { name: 'Confirm resend' })).toBeDisabled()
  await unknown.getByRole('checkbox').check()
  await unknown.getByRole('button', { name: 'Confirm resend' }).click()
  await expect(unknown.locator('.delivery-status')).toHaveText('Queued')
  await expect(record('90000005').getByRole('button')).toHaveCount(0)

  // Saving a correction refreshes the outbox independently of mark success.
  const resultRow = page.locator('tr').filter({ has: page.getByText('90000001', { exact: true }) })
  await resultRow.locator('input').fill('80')
  await resultRow.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Saved mark for approval Synthetic.', { exact: true })).toBeVisible()
  await expect(approval).toContainText('Result version 2')
  await approval.getByText('Preview stored email', { exact: true }).click()
  await expect(approval.locator('pre')).toContainText(/80(?:\.00)? \/ 100(?:\.00)?/)
  await expect(panel).toContainText('Superseded')
  await expect(panel).toContainText('Previous mark version')
  await page.getByRole('button', { name: 'Light Mode' }).click()
  await panel.scrollIntoViewIfNeeded()
  await page.screenshot({ path: test.info().outputPath('email-delivery.png') })
})
