import { expect, test } from '@playwright/test'

test('lecturer adds a student to a course using the manual form', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('Email address').fill('e2e.lecturer@example.com')
  await page.getByLabel('Password', { exact: true }).fill('TestPass123!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
  await page.goto('/courses')
  await page.getByLabel('Code', { exact: true }).fill('MANUAL101')
  await page.getByLabel('Name', { exact: true }).fill('Manual student course')
  await page.getByLabel('Year', { exact: true }).fill('2026')
  await page.getByRole('button', { name: 'Create course', exact: true }).click()
  await page.getByText('MANUAL101', { exact: true }).click()
  await page.getByLabel('Student number', { exact: true }).fill('00998877')
  await page.getByLabel('First name', { exact: true }).fill('Manual')
  await page.getByLabel('Last name', { exact: true }).fill('Student')
  await page.getByLabel('Email', { exact: true }).fill('manual.student@example.invalid')
  await page.getByRole('button', { name: 'Add student', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Student added to this course.')
  const row = page.locator('.student-table tbody tr').filter({ hasText: '00998877' })
  await expect(row).toHaveCount(1)
  await expect(row).toContainText('Manual Student')
  await expect(row).toContainText('manual.student@example.invalid')
  await expect(page.locator('.membership-row').filter({ hasText: '00998877' })).toHaveCount(1)
  await expect(page.getByLabel('Student number', { exact: true })).toHaveValue('')
})
